- name: Install Docker Service
  hosts: all
  gather_facts: false
  tasks:
  - name: check os
    assert:
      that:
        - ansible_facts['distribution'] == "Rocky"
      fail_msg: "This script is for Rocky only. {{ ansible_distribution }} detected."
      success_msg: "{{ ansible_distribution }} detected."

- name: Retrive system info
  hosts: all
  tasks:
  - shell: uname -a
    ignore_errors: yes
    changed_when: false
    register: uname_result
  - debug: msg="{{ uname_result.stdout }}"

- name: Install Docker
  hosts: all
  tasks:
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
      
    - name: Install docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)"
        dest: /usr/local/bin/docker-compose
        mode: 'a+x'
        force: yes      
